import { readFile, writeFile, mkdir, copyFile } from 'node:fs/promises';

// Keep unmodified Fontsource subsets and their licenses. Only emit the CJK
// ranges used by the authored registration labels; rerun after changing them.
const root = new URL('../../', import.meta.url);
const content = JSON.parse(
  await readFile(new URL('proxy/src/content/site.json', root), 'utf8'),
);
const codes = [
  ...new Set(
    content.registrations.flatMap(({ label }) =>
      [...label].map((c) => c.codePointAt(0)).filter((c) => c > 127),
    ),
  ),
];
let css =
  '/* Generated by scripts/orbit-fonts.mjs from the authored registration labels. */\n';
for (const family of ['noto-sans-sc']) {
  const source = await readFile(
    new URL(`node_modules/@fontsource/${family}/400.css`, root),
    'utf8',
  );
  for (const block of source.matchAll(/@font-face\s*\{[^}]+\}/g)) {
    const ranges = block[0]
      .match(/unicode-range:\s*([^;]+)/)[1]
      .split(',')
      .map((range) =>
        range
          .replace('U+', '')
          .split('-')
          .map((n) => parseInt(n, 16)),
      );
    if (
      !codes.some((code) =>
        ranges.some(([start, end = start]) => code >= start && code <= end),
      )
    )
      continue;
    css +=
      block[0].replaceAll('./files/', `@fontsource/${family}/files/`) + '\n';
  }
}
await writeFile(
  new URL('proxy/src/components/home/registration-fonts.css', root),
  css,
);
const directory = new URL('proxy/public/licenses/fonts/', root);
await mkdir(directory, { recursive: true });
for (const family of ['ibm-plex-sans', 'noto-sans-sc']) {
  await copyFile(
    new URL(`node_modules/@fontsource/${family}/LICENSE`, root),
    new URL(`${family}.txt`, directory),
  );
}
